# Generated by Django 3.1.5 on 2021-01-05 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Book Name')),
                ('category', models.CharField(choices=[('science', 'Science'), ('tech', 'Technology'), ('sports', 'Sportss'), ('ent', 'Entertainment')], max_length=50, verbose_name='category')),
                ('author', models.CharField(max_length=150, verbose_name='author')),
                ('price', models.IntegerField(default=0, verbose_name='Price')),
                ('published_on', models.DateField(verbose_name='Published on')),
                ('created_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
